### PR TITLE
Add Renovate integration

### PR DESCRIPTION
**Pull request by iBicha**
## Why
I often see in the apps that updates are available. I don't know if this is because the docker images are behind, or it's the app-store (this repo). This is an attempt to make updating things easier.

## How
This is a simple attempt to add [Renovate](https://github.com/renovatebot/renovate) - #61 

Renovate should be able to keep the apps up to date, when new docker images are out.

Additionally, a simple script will copy the version from docker-compose.yml to the config.json file to keep things in sync.

Finally, I added the Renovate Github action so you can trigger the workflow manually. But this requires the [RENOVATE_TOKEN](https://github.com/renovatebot/github-action#token) to be created.

### Notes
- The Renovate is configured so that it only renovate docker things. You can enable it up update other types of dependencies if you like.
- Here's what the [PRs](https://github.com/iBicha/runtipi-appstore/pulls/app%2Frenovate) and the [Dash](https://github.com/iBicha/runtipi-appstore/issues/created_by/app/renovate) look like on my fork
- In the PRs, each PR is changing too many files (almost all json files) - this is merely because of json formatting done by jq. Once the formatting is merged once, it should not do that again, and only the file concerned will be committed.

### CODE REVIEW

**Comment by meienberger** [comment]
This looks absolutely amazing! Thank you very much @iBicha! Can you also make it increase the `tipi_version` in the config.json? This is what triggers an update on the dashboard. Other than that I'll integrate it as soon as possible

**Comment by meienberger** [comment]
After testing locally, it looks like we need to find a way to run `renovate-app-version.sh` only on updated apps. Otherwise, it will trigger an update each time we increase the `tipi_version`. Do you think this is possible?

**Comment by meienberger** [comment]
Here is my suggestion:

in `renovate-app-version.yml` we find the name of the apps updated and run the script by providing an argument
```
- name: Get list of updated files by the last commit seperated by space
        id: updated-files
        run: |
          echo ${{github.sha}}
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | tr '\n' ' ')"

- name: Run renovate-app-version.sh on updated files
      run: |
        IFS=' ' read -ra files <<< "${{ steps.updated-files.outputs.files }}"

        for file in "${files[@]}"; do
          if [[ $file == *"docker-compose.yml"* ]]; then
            app_name=$(echo $file | cut -d'/' -f 2)
            ./.github/workflows/renovate-app-version.sh $app_name
          fi
        done
```

Then in `renovate-app-version.sh` we run the script with the app name

```
app_name=$1

# find all docker-compose files
docker_compose_files=$(find apps/$app_name -name docker-compose.yml)
```

**Comment by iBicha** [comment]
> Then in `renovate-app-version.sh` we run the script with the app name

This makes sense to me, isolated changes are better this way.

I did an update on the tipi_version, I think it will work. Let me update that github action

**Comment by iBicha** [comment]
@meienberger I don't think this is working properly yet
For example https://github.com/iBicha/runtipi-appstore/pull/34/files
The update app version https://github.com/iBicha/runtipi-appstore/actions/runs/3245696027/jobs/5323558088
Shows `nothing to commit, working tree clean`

**Comment by meienberger** [comment]
True, it looks like the command to print the modified files is not working properly

**Comment by meienberger** [comment]
Btw do I need an extra step besides the token to make it work? I ran it manually and there was no result

**Comment by iBicha** [comment]
> Btw do I need an extra step besides the token to make it work? I ran it manually and there was no result

Right! There's the self hosted and hosted version of the app. I thought the github action is enough, if not, you probably just want to configure it here on the repo https://github.com/apps/renovate (for the hosted version I guess)

**Comment by meienberger** [comment]
I managed to make it work! https://github.com/meienberger/runtipi-appstore/pull/71/files
The issue was that in action, by default it only checkout the last commit not the whole git history

**Pull request merged**
