### PR TITLE
Improve Nextcloud proxy labels and env vars

### PR DESCRIPTION
**Pull request by sethforprivacy**
These changes are sourced from many months of tuning for Nextcloud as a part of https://github.com/sethforprivacy/self-hosted-services

### CODE REVIEW

**Comment by meienberger** [comment]
Thank you very much for all those contributions! Will try to have them merged over the week-end

**Comment by sethforprivacy** [comment]
Of course, thank you *so much* for the hard work on this, it's exactly what I wanted to build but didn't have the time to.

Will be archiving my related repo and pushing users here once all my PRs are merged :)

**Comment by meienberger** [comment]
> @meienberger One question -- will the readme programmatically update with all of these, or would you like a PR that adds them to the readme in the same format as others?

I usually update the readme manually. You can add it in your PRs or I'll do it when I merge. No need to add them in the main repo since I want at some point having the list only here to avoid maintaining two lists

**Comment by sethforprivacy** [comment]
> > @meienberger One question -- will the readme programmatically update with all of these, or would you like a PR that adds them to the readme in the same format as others?
> 
> I usually update the readme manually. You can add it in your PRs or I'll do it when I merge. No need to add them in the main repo since I want at some point having the list only here to avoid maintaining two lists

PR'd a readme update that fixes some syntax and adds all PR'd apps: https://github.com/meienberger/runtipi-appstore/pull/21

**Pull request merged**
