### PR TITLE
Update tipi version and added URL environment variable

### PR DESCRIPTION
**Pull request by nsvrana**
Updated to the latest version and added an environment variable for the domain which is necessary when setting up integrations that have OAUTH2 callbacks, otherwise the callback URL is localhost, which is not functional.

One thing I am not clear on is what ${APP_DOMAIN} returns if the URL is not set to exposed inside of Tipi. Does this need to be conditional?

### CODE REVIEW

**Comment by DrMxrcy** [comment]
> Updated to the latest version and added an environment variable for the domain which is necessary when setting up integrations that have OAUTH2 callbacks, otherwise the callback URL is localhost, which is not functional.
> 
> One thing I am not clear on is what ${APP_DOMAIN} returns if the URL is not set to exposed inside of Tipi. Does this need to be conditional?

${APP_DOMAIN} will return with the IP:PORT if no domain is exposed!

**Comment by nsvrana** [comment]
I think that's fine, we will just need to have a note that OAUTH based integrations won't work without an external domain set.

**Comment by DrMxrcy** [comment]
> I think that's fine, we will just need to have a note that OAUTH based integrations won't work without an external domain set.

Thats fine, Feel free to set it in the Description!

**Comment by DrMxrcy** [comment]
Thank you for the PR!

**Pull request merged**
