### PR TITLE
 [New App] Owncast

### PR DESCRIPTION
**Pull request by HeyOsco**
In lieu of recent Twitch.tv drama, I spent some time figuring out how to integrate [Owncast](https://owncast.online/) into my RunTipi instance.

Mine is deployed here as proof! [https://owncast.atemosta.com/#](https://owncast.atemosta.com/#)

I will mention that the usual method of using Cloudflare Zero Trust Access to tunnel into the app didn't work because it wasn't able to use RTMP on port 1935 :( so I wrote a small [gist](https://gist.github.com/HeyOsco/6e8102d7d82ffaeaae16f41bef98b739) as a guide in how to expose your Owncast app and added it into the store listing if interested!

Let me know if I need do add anything else to have this added.

### CODE REVIEW

**Comment by meienberger** [comment]
Amazing, thank you very much for your contribution 🚀 Pipeline is passing, I'm gonna test it locally. I've read your guide, very useful! I'm just worried because the files `traefik.yml` and `dynamic.yml` will get overriden. The part in `dynamic.yml` can be done in the different file and loaded aswell. For the `traefik.yml` I can add it to the main repo

**Comment by HeyOsco** [comment]
Thank you taking the time to check this out, @meienberger! You are correct with with the `dynamic.yml` , it started to botch my subsequent apps I tried to expose, so I'll look into how to make a specific traefik file just for this deployment! 

> For the traefik.yml part, I can add it to the main repo
That would be awesome, thanks for doing this!

**Comment by HeyOsco** [comment]
Hey @meienberger , I made some changes based on your last review!

* I updated the GitHub gist to no longer add manually configure `traefik.yml` and `dynamic.yml`, and instead made a PR to enable TLS on Traefik's CertResolver https://github.com/meienberger/runtipi/pull/597/files
* Minor updates to the docker compose config

Let me know if this all looks good! If not, I'm happy to make any required changes!

**Comment by meienberger** [comment]
Looks good! Will do a final test and merge it. Your changes to traefik.yml will need to wait next release tho

**Comment by HeyOsco** [comment]
No worries at all! Glad you had a chance to try it out.

**Pull request merged**
