### PR TITLE
Firefly III Data Importer and cronjob for Firefly III

### PR DESCRIPTION
**Pull request by YellowWords**
Hello! I added an app for the Firefly III Data Importer. This is a standalone service from Firefly III. The maintainer of FF3 wants to separate them due to concerns about bloat among other things.

I started out adding it to the same compose file as Firefly III, however since it has a different port than the main web service I found it was actually cleaner to add it as a entirely separate app. Then you can also install them separately if you want to for whatever reason.

### CODE REVIEW

**Comment by YellowWords** [comment]
OK, so I also ended up adding [cronjob support](https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/) to Firefly III! This is used for some automated tasks such as recurring transfers and auto-budgeting.

**Comment by meienberger** [comment]
Thanks for your contribution! I'll test it out later today

**Comment by YellowWords** [comment]
@meienberger I need to fix the new app for the 1.5 HTTPS subdomains. Could you have a look at the PR after that please? I'd like to get it into master, otherwise I have to keep rebasing to get updates to my Tipi instance.

**Comment by meienberger** [comment]
Hello yes please tag me here once you are ready I'll merge it today

**Comment by YellowWords** [comment]
@meienberger No worries! It's ready for review now.

**Comment by YellowWords** [comment]
Thanks for merging! 🎉

**Comment by meienberger** [comment]
> Thanks for merging! 🎉

Thanks for your contribution

**Pull request merged**
