### PR TITLE
Add MoneroBlock

### PR DESCRIPTION
**Pull request by sethforprivacy**

### CODE REVIEW

**Comment by sethforprivacy** [comment]
Validated unexposed config.

**Comment by meienberger** [comment]
I see that the two compose files are the same. In this case only one is necessary. The process is the following:
If there is a `docker-compose.arm.yml` file AND the system is arm based. Otherwise take the `docker-compose.yml` (even on arm)

**Comment by sethforprivacy** [comment]
Ah, did not realize it was able to handle that, perfect!

**Comment by meienberger** [comment]
Thank you! I took some freedom and created a logo as the one provided was not square

**Pull request merged**
